update versions and update thread scripts

diff --git a/deb_repo/thirdreality-otbr-agent/DEBIAN/postinst b/deb_repo/thirdreality-otbr-agent/DEBIAN/postinst
--- a/deb_repo/thirdreality-otbr-agent/DEBIAN/postinst
+++ b/deb_repo/thirdreality-otbr-agent/DEBIAN/postinst
@@ -119,37 +119,62 @@ if [ "$1" = "configure" ]; then
 	/usr/bin/systemctl reload dbus
 	/usr/bin/systemctl daemon-reload
 
-	# 检查 GPIO pin 0, 27 的状态
-    if gpioget 0 27; then
-		echo "Info: Thread Device is found."
 
-		msg=$(iw dev wlan0 link 2>&1)
-		/usr/bin/systemctl start otbr-agent || true
+	#msg=$(iw dev wlan0 link 2>&1)
+	/usr/bin/systemctl start otbr-agent || true
 		
-		if [ -e "/usr/local/bin/supervisor" ]; then
-			/usr/local/bin/supervisor thread enabled || true
-		fi
+	if [ -e "/usr/local/bin/supervisor" ]; then
+		/usr/local/bin/supervisor thread enabled || true
+	fi
 
-		# 如果Home Assistant正在运行，需要停止服务，然后更新配置，再恢复服务
-		if [[ "$(/usr/bin/systemctl is-active home-assistant.service)" == "active" ]]; then
-			echo "Stopping home-assistant.service"
-			/usr/bin/systemctl stop home-assistant.service
+	# 如果Home Assistant正在运行，需要停止服务，然后更新配置，再恢复服务
+	if [[ "$(/usr/bin/systemctl is-active home-assistant.service)" == "active" ]]; then
+		echo "Stopping home-assistant.service"
+		/usr/bin/systemctl stop home-assistant.service
 
-			sync
-			add_open_thread_entry_to_config
-			sync
+		sync
+		add_open_thread_entry_to_config
+		sync
 
-			echo "Restore home-assistant.service"
-			/usr/bin/systemctl start home-assistant.service
-		else
-			echo "Skipping home-assistant.service"
-			add_open_thread_entry_to_config
-			sync
-		fi		
-    else
-		echo "Warning: Thread Device is not found !!!"
-        /usr/bin/systemctl stop otbr-agent || true
-    fi
+		echo "Restore home-assistant.service"
+		/usr/bin/systemctl start home-assistant.service
+	else
+		echo "Skipping home-assistant.service"
+		add_open_thread_entry_to_config
+		sync
+	fi	
+
+	# # 检查 GPIO pin 0, 27 的状态
+    # if gpioget 0 27; then
+	# 	echo "Info: Thread Device is found."
+
+	# 	msg=$(iw dev wlan0 link 2>&1)
+	# 	/usr/bin/systemctl start otbr-agent || true
+		
+	# 	if [ -e "/usr/local/bin/supervisor" ]; then
+	# 		/usr/local/bin/supervisor thread enabled || true
+	# 	fi
+
+	# 	# 如果Home Assistant正在运行，需要停止服务，然后更新配置，再恢复服务
+	# 	if [[ "$(/usr/bin/systemctl is-active home-assistant.service)" == "active" ]]; then
+	# 		echo "Stopping home-assistant.service"
+	# 		/usr/bin/systemctl stop home-assistant.service
+
+	# 		sync
+	# 		add_open_thread_entry_to_config
+	# 		sync
+
+	# 		echo "Restore home-assistant.service"
+	# 		/usr/bin/systemctl start home-assistant.service
+	# 	else
+	# 		echo "Skipping home-assistant.service"
+	# 		add_open_thread_entry_to_config
+	# 		sync
+	# 	fi		
+    # else
+	# 	echo "Warning: Thread Device is not found !!!"
+    #     /usr/bin/systemctl stop otbr-agent || true
+    # fi
 
 	echo "Install OTBR-Agent success."
 fi
